Add windows support
tbobm/etnotify pull request #7
Opened 2018-03-21 11:14 UTC by monkeek

2018-03-23 09:51 UTC, tbobm requested changes

2018-03-23 09:51 UTC, tbobm commented on etnotify.py
> +
Could you remove this blank line ?

2018-03-23 09:51 UTC, tbobm commented on etnotify.py
> +    platform = "linux"
Maybe this would be a bit clearer if the `platform` variable was uppercase, as it looks like a constant

2018-03-23 16:38 UTC, monkeek commented on etnotify.py
> +
Done :)

2018-03-23 16:38 UTC, monkeek commented on etnotify.py
> +    platform = "linux"
Done ;)

2018-03-28 09:26 UTC, tbobm approved these changes

2018-03-28 09:27 UTC, merged